// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function AnalyzeETLFile(arg1:string):Promise<backend.ETLAnalysisResult>;

export function ApplyEPP(arg1:number,arg2:number):Promise<string>;

export function ApplyHetero(arg1:number,arg2:number):Promise<string>;

export function ApplyMaxFrequency(arg1:number,arg2:number):Promise<string>;

export function ApplySoftParkLatency(arg1:number,arg2:number):Promise<string>;

export function CheckDYTCCapabilities():Promise<Record<string, boolean>>;

export function CheckNVIDIAStatus():Promise<backend.NVIDIAStatus>;

export function EnableDynamicLog():Promise<backend.DynamicLogResult>;

export function EnumerateGPUProcesses():Promise<Array<backend.GPUProcess>>;

export function EnumerateGPUs():Promise<Array<backend.GPUInfo>>;

export function GetCachedGPUStatus():Promise<number>;

export function GetDYTCInfo():Promise<backend.DYTCInfo>;

export function GetDispatcherInfo():Promise<backend.DispatcherInfo>;

export function GetDynamicLogStatus():Promise<boolean>;

export function GetEPOTStatus():Promise<backend.EPOTStatus>;

export function GetETLCaptureStatus():Promise<backend.ETLCaptureState>;

export function GetETLProfiles():Promise<Array<backend.ETLProfile>>;

export function GetETLTraceList():Promise<Array<backend.ETLTraceInfo>>;

export function GetGPUAutoGear():Promise<backend.GPUAutoGear>;

export function GetGPUPrefStatus():Promise<backend.GPUPrefStatus>;

export function GetGPUPrefStatusFromCache():Promise<backend.GPUPrefStatus>;

export function GetIGPUMode():Promise<backend.IGPUStatus>;

export function GetIntelDriverDownloadURL():Promise<string>;

export function GetIntelGPUFrequency():Promise<backend.IntelGPUFrequency>;

export function GetIntelGPUUtilization():Promise<number>;

export function GetLogFiles():Promise<Array<backend.LogFileInfo>>;

export function GetLogSummary():Promise<Record<string, any>>;

export function GetMLLogStatus():Promise<backend.MLLogStatus>;

export function GetModeCheckInfo():Promise<backend.ModeCheckInfo>;

export function GetNPUDeviceInfo():Promise<backend.NPUDeviceInfo>;

export function GetNPUDeviceInfoWrapper():Promise<backend.NPUDeviceInfo|string>;

export function GetNPUDeviceMetrics(arg1:number):Promise<backend.NPUDeviceMetrics>;

export function GetNPUDeviceOverview(arg1:number):Promise<backend.NPUDeviceOverview>;

export function GetNPUDeviceProperties(arg1:number):Promise<backend.NPUDeviceProperties>;

export function GetNPUFullReport():Promise<backend.NPUFullReport>;

export function GetNPUPowerStatus(arg1:number):Promise<backend.NPUPowerStatus>;

export function GetNPUREport():Promise<string>;

export function GetNPUSDKInfo():Promise<backend.NPUSDKInfo>;

export function GetPPMSettings():Promise<backend.PPMSettings>;

export function GetPinnedDYTCMode():Promise<string>;

export function GetSSDInfo():Promise<Array<backend.SSDInfo>>;

export function GetServiceStatus():Promise<string>;

export function GetSystemInfo():Promise<backend.SystemInfo>;

export function IsElevated():Promise<boolean>;

export function NPUGetDVFSMode(arg1:number):Promise<string>;

export function NPUSetDVFSMode(arg1:number,arg2:string):Promise<string>;

export function OpenFolder(arg1:string):Promise<void>;

export function PinDYTCMode(arg1:string):Promise<void>;

export function ReadLogTail(arg1:number):Promise<string>;

export function ResetNPUDefaults(arg1:number):Promise<backend.NPUPowerAction>;

export function RestartService():Promise<string>;

export function RestoreDefaults():Promise<string>;

export function SetDYTCMode(arg1:string):Promise<string>;

export function SetGEEKMode(arg1:boolean):Promise<string>;

export function SetGPUAutoGear(arg1:number):Promise<backend.SetResult>;

export function SetIGPUMode(arg1:number):Promise<backend.SetResult>;

export function SetIntelGPUFrequencyRange(arg1:number,arg2:number):Promise<backend.IntelGPUFreqTestResult>;

export function SetNPUClockLock(arg1:number,arg2:number,arg3:number):Promise<backend.NPUPowerAction>;

export function SetNPUMode(arg1:number,arg2:string):Promise<backend.NPUPowerAction>;

export function SetODV(arg1:number,arg2:number):Promise<string>;

export function SetPowerSettingRaw(arg1:string,arg2:number,arg3:number):Promise<string>;

export function SetSSDMode(arg1:number,arg2:number):Promise<backend.SSDModeResult>;

export function StartETLCapture(arg1:string,arg2:number):Promise<backend.ETLCaptureState>;

export function StartGPUStatusWatcher():Promise<void>;

export function StartMLScenarioCapture():Promise<backend.MLLogStatus>;

export function StartService():Promise<string>;

export function StopETLCapture():Promise<backend.ETLTraceInfo>;

export function StopGPUStatusWatcher():Promise<void>;

export function StopMLScenarioCapture():Promise<backend.MLLogStatus>;

export function StopService():Promise<string>;

export function TestIntelGPUFrequency(arg1:string):Promise<backend.IntelGPUFreqTestResult>;

export function UninstallDTT():Promise<string>;

export function UninstallDTTUI():Promise<string>;

export function UninstallDispatcher():Promise<backend.UninstallResult>;

export function UnpinDYTCMode():Promise<void>;
