// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyEPP(arg1, arg2) {
  return window['go']['main']['App']['ApplyEPP'](arg1, arg2);
}

export function ApplyHetero(arg1, arg2) {
  return window['go']['main']['App']['ApplyHetero'](arg1, arg2);
}

export function ApplyMaxFrequency(arg1, arg2) {
  return window['go']['main']['App']['ApplyMaxFrequency'](arg1, arg2);
}

export function ApplySoftParkLatency(arg1, arg2) {
  return window['go']['main']['App']['ApplySoftParkLatency'](arg1, arg2);
}

export function CheckDYTCCapabilities() {
  return window['go']['main']['App']['CheckDYTCCapabilities']();
}

export function CheckNVIDIAStatus() {
  return window['go']['main']['App']['CheckNVIDIAStatus']();
}

export function EnumerateGPUProcesses() {
  return window['go']['main']['App']['EnumerateGPUProcesses']();
}

export function EnumerateGPUs() {
  return window['go']['main']['App']['EnumerateGPUs']();
}

export function GetDYTCInfo() {
  return window['go']['main']['App']['GetDYTCInfo']();
}

export function GetDispatcherInfo() {
  return window['go']['main']['App']['GetDispatcherInfo']();
}

export function GetIGPUMode() {
  return window['go']['main']['App']['GetIGPUMode']();
}

export function GetLogFiles() {
  return window['go']['main']['App']['GetLogFiles']();
}

export function GetLogSummary() {
  return window['go']['main']['App']['GetLogSummary']();
}

export function GetMLLogStatus() {
  return window['go']['main']['App']['GetMLLogStatus']();
}

export function GetModeCheckInfo() {
  return window['go']['main']['App']['GetModeCheckInfo']();
}

export function GetPPMSettings() {
  return window['go']['main']['App']['GetPPMSettings']();
}

export function GetPinnedDYTCMode() {
  return window['go']['main']['App']['GetPinnedDYTCMode']();
}

export function GetSSDInfo() {
  return window['go']['main']['App']['GetSSDInfo']();
}

export function GetServiceStatus() {
  return window['go']['main']['App']['GetServiceStatus']();
}

export function GetSystemInfo() {
  return window['go']['main']['App']['GetSystemInfo']();
}

export function PinDYTCMode(arg1) {
  return window['go']['main']['App']['PinDYTCMode'](arg1);
}

export function ReadLogTail(arg1) {
  return window['go']['main']['App']['ReadLogTail'](arg1);
}

export function RestartService() {
  return window['go']['main']['App']['RestartService']();
}

export function RestoreDefaults() {
  return window['go']['main']['App']['RestoreDefaults']();
}

export function SetDYTCMode(arg1) {
  return window['go']['main']['App']['SetDYTCMode'](arg1);
}

export function SetGEEKMode(arg1) {
  return window['go']['main']['App']['SetGEEKMode'](arg1);
}

export function SetIGPUMode(arg1) {
  return window['go']['main']['App']['SetIGPUMode'](arg1);
}

export function SetODV(arg1, arg2) {
  return window['go']['main']['App']['SetODV'](arg1, arg2);
}

export function SetPowerSettingRaw(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetPowerSettingRaw'](arg1, arg2, arg3);
}

export function SetSSDMode(arg1, arg2) {
  return window['go']['main']['App']['SetSSDMode'](arg1, arg2);
}

export function StartMLScenarioCapture() {
  return window['go']['main']['App']['StartMLScenarioCapture']();
}

export function StartService() {
  return window['go']['main']['App']['StartService']();
}

export function StopMLScenarioCapture() {
  return window['go']['main']['App']['StopMLScenarioCapture']();
}

export function StopService() {
  return window['go']['main']['App']['StopService']();
}

export function UnpinDYTCMode() {
  return window['go']['main']['App']['UnpinDYTCMode']();
}
