// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeETLFile(arg1) {
  return window['go']['main']['App']['AnalyzeETLFile'](arg1);
}

export function ApplyEPP(arg1, arg2) {
  return window['go']['main']['App']['ApplyEPP'](arg1, arg2);
}

export function ApplyHetero(arg1, arg2) {
  return window['go']['main']['App']['ApplyHetero'](arg1, arg2);
}

export function ApplyMaxFrequency(arg1, arg2) {
  return window['go']['main']['App']['ApplyMaxFrequency'](arg1, arg2);
}

export function ApplySoftParkLatency(arg1, arg2) {
  return window['go']['main']['App']['ApplySoftParkLatency'](arg1, arg2);
}

export function CheckAllToolkitInstalled() {
  return window['go']['main']['App']['CheckAllToolkitInstalled']();
}

export function CheckDYTCCapabilities() {
  return window['go']['main']['App']['CheckDYTCCapabilities']();
}

export function CheckNVIDIAStatus() {
  return window['go']['main']['App']['CheckNVIDIAStatus']();
}

export function CheckToolkitInstalled(arg1) {
  return window['go']['main']['App']['CheckToolkitInstalled'](arg1);
}

export function EnableDynamicLog() {
  return window['go']['main']['App']['EnableDynamicLog']();
}

export function EnumerateGPUProcesses() {
  return window['go']['main']['App']['EnumerateGPUProcesses']();
}

export function EnumerateGPUs() {
  return window['go']['main']['App']['EnumerateGPUs']();
}

export function GetCachedGPUStatus() {
  return window['go']['main']['App']['GetCachedGPUStatus']();
}

export function GetDYTCInfo() {
  return window['go']['main']['App']['GetDYTCInfo']();
}

export function GetDispatcherInfo() {
  return window['go']['main']['App']['GetDispatcherInfo']();
}

export function GetDynamicLogStatus() {
  return window['go']['main']['App']['GetDynamicLogStatus']();
}

export function GetEPOTStatus() {
  return window['go']['main']['App']['GetEPOTStatus']();
}

export function GetETLCaptureStatus() {
  return window['go']['main']['App']['GetETLCaptureStatus']();
}

export function GetETLProfiles() {
  return window['go']['main']['App']['GetETLProfiles']();
}

export function GetETLTraceList() {
  return window['go']['main']['App']['GetETLTraceList']();
}

export function GetGPUAutoGear() {
  return window['go']['main']['App']['GetGPUAutoGear']();
}

export function GetGPUPrefStatus() {
  return window['go']['main']['App']['GetGPUPrefStatus']();
}

export function GetGPUPrefStatusFromCache() {
  return window['go']['main']['App']['GetGPUPrefStatusFromCache']();
}

export function GetIGPUMode() {
  return window['go']['main']['App']['GetIGPUMode']();
}

export function GetInstalledToolkitTools() {
  return window['go']['main']['App']['GetInstalledToolkitTools']();
}

export function GetIntelDriverDownloadURL() {
  return window['go']['main']['App']['GetIntelDriverDownloadURL']();
}

export function GetIntelGPUFrequency() {
  return window['go']['main']['App']['GetIntelGPUFrequency']();
}

export function GetIntelGPUUtilization() {
  return window['go']['main']['App']['GetIntelGPUUtilization']();
}

export function GetLogFiles() {
  return window['go']['main']['App']['GetLogFiles']();
}

export function GetLogSummary() {
  return window['go']['main']['App']['GetLogSummary']();
}

export function GetMLLogStatus() {
  return window['go']['main']['App']['GetMLLogStatus']();
}

export function GetModeCheckInfo() {
  return window['go']['main']['App']['GetModeCheckInfo']();
}

export function GetNPUDeviceInfo() {
  return window['go']['main']['App']['GetNPUDeviceInfo']();
}

export function GetNPUDeviceInfoWrapper() {
  return window['go']['main']['App']['GetNPUDeviceInfoWrapper']();
}

export function GetNPUDeviceMetrics(arg1) {
  return window['go']['main']['App']['GetNPUDeviceMetrics'](arg1);
}

export function GetNPUDeviceOverview(arg1) {
  return window['go']['main']['App']['GetNPUDeviceOverview'](arg1);
}

export function GetNPUDeviceProperties(arg1) {
  return window['go']['main']['App']['GetNPUDeviceProperties'](arg1);
}

export function GetNPUFullReport() {
  return window['go']['main']['App']['GetNPUFullReport']();
}

export function GetNPUPowerStatus(arg1) {
  return window['go']['main']['App']['GetNPUPowerStatus'](arg1);
}

export function GetNPUREport() {
  return window['go']['main']['App']['GetNPUREport']();
}

export function GetNPUSDKInfo() {
  return window['go']['main']['App']['GetNPUSDKInfo']();
}

export function GetPPMDrivers() {
  return window['go']['main']['App']['GetPPMDrivers']();
}

export function GetPPMPlatformInfo() {
  return window['go']['main']['App']['GetPPMPlatformInfo']();
}

export function GetPPMSettings() {
  return window['go']['main']['App']['GetPPMSettings']();
}

export function GetPinnedDYTCMode() {
  return window['go']['main']['App']['GetPinnedDYTCMode']();
}

export function GetSSDInfo() {
  return window['go']['main']['App']['GetSSDInfo']();
}

export function GetServiceStatus() {
  return window['go']['main']['App']['GetServiceStatus']();
}

export function GetSystemInfo() {
  return window['go']['main']['App']['GetSystemInfo']();
}

export function GetToolkitInstallDir() {
  return window['go']['main']['App']['GetToolkitInstallDir']();
}

export function GetToolkitProgress(arg1) {
  return window['go']['main']['App']['GetToolkitProgress'](arg1);
}

export function GetToolkitTools() {
  return window['go']['main']['App']['GetToolkitTools']();
}

export function InstallToolkitTool(arg1) {
  return window['go']['main']['App']['InstallToolkitTool'](arg1);
}

export function IsElevated() {
  return window['go']['main']['App']['IsElevated']();
}

export function IsToolkitBusy(arg1) {
  return window['go']['main']['App']['IsToolkitBusy'](arg1);
}

export function NPUGetDVFSMode(arg1) {
  return window['go']['main']['App']['NPUGetDVFSMode'](arg1);
}

export function NPUSetDVFSMode(arg1, arg2) {
  return window['go']['main']['App']['NPUSetDVFSMode'](arg1, arg2);
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function OpenTestMode() {
  return window['go']['main']['App']['OpenTestMode']();
}

export function OpenToolkitFolder() {
  return window['go']['main']['App']['OpenToolkitFolder']();
}

export function PinDYTCMode(arg1) {
  return window['go']['main']['App']['PinDYTCMode'](arg1);
}

export function ReadLogTail(arg1) {
  return window['go']['main']['App']['ReadLogTail'](arg1);
}

export function ResetNPUDefaults(arg1) {
  return window['go']['main']['App']['ResetNPUDefaults'](arg1);
}

export function RestartService() {
  return window['go']['main']['App']['RestartService']();
}

export function RestoreDefaults() {
  return window['go']['main']['App']['RestoreDefaults']();
}

export function RunToolkitTool(arg1) {
  return window['go']['main']['App']['RunToolkitTool'](arg1);
}

export function SetDYTCMode(arg1) {
  return window['go']['main']['App']['SetDYTCMode'](arg1);
}

export function SetGEEKMode(arg1) {
  return window['go']['main']['App']['SetGEEKMode'](arg1);
}

export function SetGPUAutoGear(arg1) {
  return window['go']['main']['App']['SetGPUAutoGear'](arg1);
}

export function SetIGPUMode(arg1) {
  return window['go']['main']['App']['SetIGPUMode'](arg1);
}

export function SetIntelGPUFrequencyRange(arg1, arg2) {
  return window['go']['main']['App']['SetIntelGPUFrequencyRange'](arg1, arg2);
}

export function SetNPUClockLock(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetNPUClockLock'](arg1, arg2, arg3);
}

export function SetNPUMode(arg1, arg2) {
  return window['go']['main']['App']['SetNPUMode'](arg1, arg2);
}

export function SetODV(arg1, arg2) {
  return window['go']['main']['App']['SetODV'](arg1, arg2);
}

export function SetPowerSettingRaw(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetPowerSettingRaw'](arg1, arg2, arg3);
}

export function SetSSDMode(arg1, arg2) {
  return window['go']['main']['App']['SetSSDMode'](arg1, arg2);
}

export function StartETLCapture(arg1, arg2) {
  return window['go']['main']['App']['StartETLCapture'](arg1, arg2);
}

export function StartGPUStatusWatcher() {
  return window['go']['main']['App']['StartGPUStatusWatcher']();
}

export function StartMLScenarioCapture() {
  return window['go']['main']['App']['StartMLScenarioCapture']();
}

export function StartService() {
  return window['go']['main']['App']['StartService']();
}

export function StopETLCapture() {
  return window['go']['main']['App']['StopETLCapture']();
}

export function StopGPUStatusWatcher() {
  return window['go']['main']['App']['StopGPUStatusWatcher']();
}

export function StopMLScenarioCapture() {
  return window['go']['main']['App']['StopMLScenarioCapture']();
}

export function StopService() {
  return window['go']['main']['App']['StopService']();
}

export function TestIntelGPUFrequency(arg1) {
  return window['go']['main']['App']['TestIntelGPUFrequency'](arg1);
}

export function UninstallDTT() {
  return window['go']['main']['App']['UninstallDTT']();
}

export function UninstallDTTUI() {
  return window['go']['main']['App']['UninstallDTTUI']();
}

export function UninstallDispatcher() {
  return window['go']['main']['App']['UninstallDispatcher']();
}

export function UninstallToolkitTool(arg1) {
  return window['go']['main']['App']['UninstallToolkitTool'](arg1);
}

export function UnpinDYTCMode() {
  return window['go']['main']['App']['UnpinDYTCMode']();
}
